apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 2
  strategy:
   type: RollingUpdate
   rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nodejs-container
        image: rcavinash123/cubusnodejs:v1.0.9
        ports:
        - containerPort: 5000
      nodeSelector:
        nodeos: windows
  
